app/ig/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required


ig = Blueprint('ig', __name__, template_folder='ig_templates')

from .forms import CreatePostForm, UpdatePostForm
from app.models import db, Post


@ig.route('/posts')
def posts():
    posts = Post.query.all()[::-1]
    return render_template('posts.html', posts = posts)

@ig.route('/create-post', methods=["GET", "POST"])
@login_required
def createPost():
    form = CreatePostForm()
    if request.method == "POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            post = Post(title, img_url, caption, current_user.id)

            db.session.add(post)
            db.session.commit()   

            return redirect(url_for('home'))         

    return render_template('createpost.html', form = form)

@ig.route('/posts/<int:post_id>')
def individualPost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return redirect(url_for('ig.posts'))
    return render_template('individual_post.html', post = post)

@ig.route('/posts/update/<int:post_id>', methods=["GET","POST"])
@login_required
def updatePost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return redirect(url_for('ig.posts'))
    if post.user_id != current_user.id:
        return redirect(url_for('ig.posts'))
    form = UpdatePostForm()
    if request.method == "POST":
        if form.validate():
            title = form.title.data
            img_url = form.img_url.data
            caption = form.caption.data

            # update the original post
            post.title = title
            post.image = img_url
            post.caption = caption

            db.session.commit()   

            return redirect(url_for('home'))         
    return render_template('updatepost.html', form=form, post = post)


@ig.route('/posts/delete/<int:post_id>', methods=["POST"])
@login_required
def deletePost(post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post is None:
        return redirect(url_for('ig.posts'))
    if post.user_id != current_user.id:
        return redirect(url_for('ig.posts'))

    db.session.delete(post)
    db.session.commit()
               
    return redirect(url_for('ig.posts'))

app/pokemon/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
import requests as r

pokemon = Blueprint('pokemon', __name__, template_folder="pokemon_templates")

from app.models import db, Pokemon

@pokemon.route('/my-pokemon')
def showPokedex():
    pokedex = Pokemon.query.all()[::-1]
    return render_template('my-pokemon.html', pokedex=pokedex)

@pokemon.route('/pokedex', methods=["GET", "POST"])
def addToPokedex():
    name = request.form.to_dict()['name']
    name = name.lower().strip()
    data = r.get(f"https://pokeapi.co/api/v2/pokemon/{name}")
    if data.status_code == 200:
        my_data = data.json()
        abilities = my_data['abilities']
        my_abilities = []

        
        for item in abilities:
            my_abilities.append(item['ability']['name'])
        print(my_abilities)

        poke_name = name
        image = my_data['sprites']['front_default']
        
        if len(my_abilities) == 3:
            ability1 = my_abilities[0]
            ability2 = my_abilities[1]
            ability3 = my_abilities[2]
        elif len(my_abilities) == 2:
            ability1 = my_abilities[0]
            ability2 = my_abilities[1]
            ability3 = 'none'
        elif len(my_abilities) == 1:
            ability1 = my_abilities[0]
            ability2 = 'none'
            ability3 = 'none'


        pokemon = Pokemon(poke_name, image, ability1, ability2, ability3)

        # check for pokemon already in database and only adds new pokemon
        if Pokemon.query.filter_by(name=poke_name).first():
            print('Pokemon already exists.')
        else:
            db.session.add(pokemon)
            db.session.commit()

    return redirect(url_for('pokemon.showPokedex'))


@pokemon.route('/pokemon', methods=["POST"])
def myPokemon():
    name = request.form.to_dict()['name']
    name = name.lower().strip()
    data = r.get(f"https://pokeapi.co/api/v2/pokemon/{name}")
    if data.status_code == 200:
        my_data = data.json()
        abilities = my_data['abilities']
        my_abilities = []
        for item in abilities:
            my_abilities.append((item['ability']['name']))
        my_img = my_data['sprites']['front_default']
        return render_template('pokemon.html', abilities=my_abilities, img_url=my_img, name=name)
    return redirect(url_for('home'))

app/shop/routes.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import current_user, login_required


shop = Blueprint('shop', __name__, template_folder='shop_templates')

from app.models import db, Product, Cart
from .forms import CreateProductForm

@shop.route('/products')
@login_required
def allProducts():
    products = Product.query.all()
    return render_template('shop.html', products=products)

@shop.route('/products/<int:product_id>')
@login_required
def individualProduct(product_id):
    product = Product.query.filter_by(id=product_id).first()
    if product is None:
        return redirect(url_for('shop.allProducts'))
    return render_template('individual_product.html', product = product)

# CART FUNCTIONALITY
@shop.route('/cart')
@login_required
def showCart():
    cart = Cart.query.filter_by(user_id=current_user.id)
    count = {}
    for item in cart:
        count[item.product_id] = count.get(item.product_id, 0) + 1
    
    cart_products = []
    for product_id in count:
        product_info = Product.query.filter_by(id=product_id).first().to_dict()
        product_info["quantity"] = count[product_id]
        product_info['subtotal'] = product_info['quantity'] * product_info['price']
        cart_products.append(product_info)

    return render_template('show_cart.html', cart = cart_products)


@shop.route('/cart/add/<int:product_id>')
def addToCart(product_id):
    cart_item = Cart(current_user.id, product_id)
    db.session.add(cart_item)
    db.session.commit()
    return redirect(url_for('shop.allProducts'))

@shop.route('/cart/add', methods=["POST"])
def addToCart2():
    product_id = request.form.to_dict()['product_id']
    cart_item = Cart(current_user.id, product_id)
    db.session.add(cart_item)
    db.session.commit()
    return redirect(url_for('shop.individualProduct', product_id=product_id))



# ADMIN CREATE PRODUCT PAGE
@shop.route('/products/create')
@login_required
def createProduct():
    if current_user.is_admin:
        form = CreateProductForm()
        if request.method == "POST":
            if form.validate():
                product_name = form.product_name.data
                img_url = form.img_url.data
                description = form.description.data
                price = form.price.data

                product = Product(product_name, img_url, description, price)

                db.session.add(product)
                db.session.commit()   

                return redirect(url_for('shop.createProduct'))         

        return render_template('create_product.html', form = form)
    else:
        return redirect(url_for('shop.allProducts'))   

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h2>This is the about page</h2>


{% endblock content %}




    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    
</head>
<body>
    {% include 'navbar.html' %}

    

    <main class="container">

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}

                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                     </div>

                {% endfor  %}
            {% endif %}


        {% endwith %}

        {% block content %}


        
        {% endblock content %}
    </main>




    <script src="https://kit.fontawesome.com/3d81577920.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello World</h1>
    <ul>
        {% for name in my_list %}
            {% if name == "Shoha" %}
                <li><b>{{ name }}</b></li>
            {% else %}
                <li>{{ name }}</li>
            {% endif %}
        {% endfor %}


    </ul>


{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('shop.allProducts') }}">Shop</a>
                </li>

                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('ig.createPost') }}">Create Post</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logMeOut') }}">Log Out</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logMeIn') }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signMeUp') }}">Sign Up</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{ current_user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('shop.showCart') }}" tabindex="-1" aria-disabled="true"><i class="fas fa-shopping-cart"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('pokemon.showPokedex') }}">Pokedex</a>
                </li>
            </ul>
            <form class="d-flex" action="{{ url_for('pokemon.myPokemon') }}" method="POST">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="name">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <form class="d-flex" action="{{ url_for('pokemon.addToPokedex') }}" method="POST">
                <input class="form-control me-2" type="search" placeholder="Add to Pokedex" aria-label="Search" name="name">
                <button class="btn btn-outline-success" type="submit">Add</button>
            </form>
        </div>
    </div>
</nav>